name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Push Backend to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          SUBTREE_SHA=$(git subtree split --prefix Backend main)

          git push --force \
            "https://AhmadYarAI:${HF_TOKEN}@huggingface.co/spaces/AhmadYarAI/smart-query-routing-email-automation-system" \
            "${SUBTREE_SHA}:main"